const sequelize = require("../config/connection");
const { Animal } = require("../models");

const animalData = [
  {
    image_link:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/African_Elephant_%28Loxodonta_africana%29_male_%2817289351322%29.jpg/547px-African_Elephant_%28Loxodonta_africana%29_male_%2817289351322%29.jpg",
    name: "African Bush Elephant",
    latin_name: "Loxodonta africana africana",
    lifespan: "60 - 70 years",
    animal_type: "Mammal",
    geo_range: "central and southern Africa",
    habitat: "Forest, savannah and flood plains",
    diet: "Grass, Fruit, Roots",
    active_time: "Diurnal",
    length_min: "10 ft",
    length_max: "12 ft",
    weight_min: "7,900 lbs",
    weight_max: "12,000 lbs",
  },
  {
    image_link:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Komodo_dragon_with_tongue.jpg/220px-Komodo_dragon_with_tongue.jpg",
    name: "Komodo Dragon",
    latin_name: "Varanus komodoensis",
    lifespan: "25 - 40 years",
    animal_type: "Reptile",
    geo_range: "Indonesia and surrounding islands",
    habitat: "Open woodland and hillsides",
    diet: "Pigs, Deer, Water Buffalo",
    active_time: "Diurnal",
    length_min: "6.6 ft",
    length_max: "10.3 ft",
    weight_min: "150 lbs",
    weight_max: "300 lbs",
  },
  {
    image_link:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Plains_Zebra_Equus_quagga.jpg/220px-Plains_Zebra_Equus_quagga.jpg",
    name: "Zebra",
    latin_name: "Equus zebra, Equus quagga, Equus grevyi",
    lifespan: "20 - 30 years",
    animal_type: "Mammal",
    geo_range: "Eastern and Southern Africa",
    habitat: "Open grassland and plains",
    diet: "Grasses, Leaves, Buds",
    active_time: "Diurnal",
    length_min: "6.6 ft",
    length_max: "9 ft",
    weight_min: "485 lbs",
    weight_max: "893 lbs",
  },
  {
    image_link:
      "https://upload.wikimedia.org/wikipedia/commons/9/9f/Cuttlefish_komodo_large.jpg",
    name: "Cuttlefish",
    latin_name: "Sepiida",
    lifespan: "2 years",
    animal_type: "Cephalopod",
    geo_range: "Worldwide",
    habitat: "Coastal and deeper waters",
    diet: "Crab, Shrimp, Fish",
    active_time: "Day and night",
    length_min: "5.9 in",
    length_max: "20 in",
    weight_min: "6.6 lbs",
    weight_max: "23 lbs",
  },
  {
    image_link:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Peacock_Plumage.jpg/220px-Peacock_Plumage.jpg",
    name: "Peacock",
    latin_name: "Pavo cristatus",
    lifespan: "12 - 20 years",
    animal_type: "bird",
    geo_range: "Africa and Asia",
    habitat: "Desert and savanna areas",
    diet: "Grains, Seeds, Insects",
    active_time: "Diurnal",
    length_min: "34 in",
    length_max: "42 in",
    weight_min: "6 lbs",
    weight_max: "13.2lbs",
  },
  {
    image_link:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/African_wild_dog_%28Lycaon_pictus_pictus%29.jpg/440px-African_wild_dog_%28Lycaon_pictus_pictus%29.jpg",
    name: "Painted Dog",
    latin_name: "Lycaon pictus",
    lifespan: "10 - 13 years",
    animal_type: "Mammal",
    geo_range: "sub-Saharan Africa",
    habitat: "Open plains and savanna",
    diet: "Antelope, Warthog, Rodents",
    active_time: "Diurnal",
    length_min: "29 in",
    length_max: "43 in",
    weight_min: "39 lbs",
    weight_max: "79 lbs",
  },
  {
    image_link:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Aardvark_%28Orycteropus_afer%29.jpg/440px-Aardvark_%28Orycteropus_afer%29.jpg",
    name: "Aardvark",
    latin_name: "Orycteropus afer",
    lifespan: "23 years",
    animal_type: "Mammal",
    geo_range: "sub-Saharan Africa",
    habitat: "Sandy and clay soil",
    diet: "Termites, Ants",
    active_time: "Nocturnal",
    length_min: "3.4 ft",
    length_max: "7.3ft",
    weight_min: "130 lbs",
    weight_max: "180 lbs",
  },
  {
    image_link:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Civettictis_civetta_11.jpg/440px-Civettictis_civetta_11.jpg",
    name: "African Civet",
    latin_name: "Civettictis civetta",
    lifespan: "15 - 20 years",
    animal_type: "Mammal",
    geo_range: "sub-Saharan Africa",
    habitat: "Tropical rainforest",
    diet: "Rodents, Snakes, Frogs",
    active_time: "Nocturnal",
    length_min: "2.2 ft",
    length_max: "2.8 ft",
    weight_min: "3 lbs",
    weight_max: "10 lbs",
  },
  {
    image_link:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Myresluger2.jpg/440px-Myresluger2.jpg",
    name: "Anteater",
    latin_name: "Myrmecophaga Tridactyla",
    lifespan: "9 - 20 years",
    animal_type: "Mammal",
    geo_range: "Central and South America",
    habitat: "Forest and grasslands",
    diet: "Ants, Termites, Insects",
    active_time: "Diurnal",
    length_min: "3 ft",
    length_max: "7 ft",
    weight_min: "40 lbs",
    weight_max: "88 lbs",
  },
  {
    image_link:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Aye-aye_at_night_in_the_wild_in_Madagascar.jpg/340px-Aye-aye_at_night_in_the_wild_in_Madagascar.jpg",
    name: "Aye-aye",
    latin_name: "Daubentonia madagascariensis",
    lifespan: "10 - 23 years",
    animal_type: "Mammal",
    geo_range: "Eastern coast of Madagascar",
    habitat: "Dense, tropical rainforest",
    diet: "Insects, Larvae, Fruit",
    active_time: "Nocturnal",
    length_min: "12 in",
    length_max: "15 in",
    weight_min: "4 lbs",
    weight_max: "6 lbs",
  },
  {
    image_link:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Perameles_gunni.jpg/440px-Perameles_gunni.jpg",
    name: "Bandicoot",
    latin_name: "Perameles",
    lifespan: "3-7 years",
    animal_type: "Mammal",
    geo_range: "Australia and New Guinea",
    habitat: "Forest, rainforest and jungle",
    diet: "Insects, Fruit, Seeds",
    active_time: "Nocturnal",
    length_min: "11 in",
    length_max: "32 in",
    weight_min: "0.4 lbs",
    weight_max: "3.5 lbs",
  },
  {
    image_link:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/American_Beaver.jpg/440px-American_Beaver.jpg",
    name: "Beaver",
    latin_name: "Castor",
    lifespan: "10-12 years",
    animal_type: "Mammal",
    geo_range: "",
    habitat: "Freshwater Ecosystems",
    diet: "Tree bark, Twigs, Soft Vegetation like Willows, Water Lilies, Cattails, & Watercress",
    active_time: "Nocturnal",
    length_min: "31 in",
    length_max: "47 in",
    weight_min: "24 lbs",
    weight_max: "71 lbs",
  },
  {
    image_link:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Amazona_autumnalis_-side_-Belize_Zoo-8-3c.jpg/440px-Amazona_autumnalis_-side_-Belize_Zoo-8-3c.jpg",
    name: "Amazon Parrot",
    latin_name: "Amazona",
    lifespan: "Up to 100 years",
    animal_type: "Bird",
    geo_range: "S America, Mexico, Caribbean",
    habitat:
      "Woodlands, savannas, rainforests, palm groves, cloud forests, moist forests, mountain forests",
    diet: "seeds, nuts, fruits, berries, and vegetation",
    active_time: "Diurnal",
    length_min: "10 in",
    length_max: "32 oz",
    weight_min: "7.6 oz",
    weight_max: "32 oz",
  },
  {
    image_link: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Double-wattled_Cassowary_or_Kasuari_%28Casuarius_casuarius%29.jpg/440px-Double-wattled_Cassowary_or_Kasuari_%28Casuarius_casuarius%29.jpg",
    name: "Cassowary",
    latin_name: "Casuarius",
    lifespan: "40 - 60 years",
    animal_type: "Bird",
    geo_range: "Northern Australia, New Guinea, and surrounding islands",
    habitat: "Wet tropical forests",
    diet: "Insects, Grass, Fungi",
    active_time: "Diurnal",
    length_min: "3.3 ft",
    length_max: "5.6 ft",
    weight_min: "55 lbs",
    weight_max: "129 lbs",
  },
    {
        image_link:"https://upload.wikimedia.org/wikipedia/commons/a/a3/Aptenodytes_forsteri_-Snow_Hill_Island%2C_Antarctica_-adults_and_juvenile-8.jpg",
        name:"Emporer Penguin",
        latin_name:"Aptenodytes forsteri",
        lifespan:"15 - 50 years",
        animal_type:"Bird",
        geo_range:"Antarctica",
        habitat:"Compact sea-ice and ocean",
        diet:"Fish, Krill, Squid",
        active_time:"Diurnal",
        length_min:"39 in",
        length_max:"47 in",
        weight_min:"49 lbs",
        weight_max:"99 lbs"
    },
        {
        image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Balaeniceps_rex.jpg/440px-Balaeniceps_rex.jpg",
        name:"Shoebill Stork",
        latin_name:"Balaeniceps rex",
        lifespan:"Up to 35 years",
        animal_type:"Bird",
        geo_range:"East Africa",
        habitat:"Wetlands",
        diet:"Fish, snakes, frogs, turtles, lizards",
        active_time:"Diurnal",
        length_min:"3.5 ft",
        length_max:"4.5 ft",
        weight_min:"11 lbs",
        weight_max:"12 lbs"
    },
            // {
    //     image_link:"",
    //     name:"",
    //     latin_name:"",
    //     lifespan:"",
    //     animal_type:"",
    //     geo_range:"",
    //     habitat:"",
    //     diet:"",
    //     active_time:"",
    //     length_min:"",
    //     length_max:"",
    //     weight_min:" lbs",
    //     weight_max:" lbs"
    // },
            // {
    //     image_link:"",
    //     name:"",
    //     latin_name:"",
    //     lifespan:"",
    //     animal_type:"",
    //     geo_range:"",
    //     habitat:"",
    //     diet:"",
    //     active_time:"",
    //     length_min:"",
    //     length_max:"",
    //     weight_min:" lbs",
    //     weight_max:" lbs"
    // },
            // {
    //     image_link:"",
    //     name:"",
    //     latin_name:"",
    //     lifespan:"",
    //     animal_type:"",
    //     geo_range:"",
    //     habitat:"",
    //     diet:"",
    //     active_time:"",
    //     length_min:"",
    //     length_max:"",
    //     weight_min:" lbs",
    //     weight_max:" lbs"
    // },
];
const seedData = async () => {
  await sequelize.sync({ force: true });
  const animals = await Animal.bulkCreate(animalData);
};
seedData();
