const sequelize = require("../config/connection");
const { Animal } = require("../models");

const animalData = [
  {
    image_link:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/African_Elephant_%28Loxodonta_africana%29_male_%2817289351322%29.jpg/547px-African_Elephant_%28Loxodonta_africana%29_male_%2817289351322%29.jpg",
    name: "African Bush Elephant",
    latin_name: "Loxodonta africana africana",
    lifespan: "60 - 70 years",
    animal_type: "Mammal",
    geo_range: "central and southern Africa",
    habitat: "Forest, savannah and flood plains",
    diet: "Grass, Fruit, Roots",
    active_time: "Diurnal",
    length_min: "10 ft",
    length_max: "12 ft",
    weight_min: "7,900 lbs",
    weight_max: "12,000 lbs",
  },
  {
    image_link:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Komodo_dragon_with_tongue.jpg/220px-Komodo_dragon_with_tongue.jpg",
    name: "Komodo Dragon",
    latin_name: "Varanus komodoensis",
    lifespan: "25 - 40 years",
    animal_type: "Reptile",
    geo_range: "Indonesia and surrounding islands",
    habitat: "Open woodland and hillsides",
    diet: "Pigs, Deer, Water Buffalo",
    active_time: "Diurnal",
    length_min: "6.6 ft",
    length_max: "10.3 ft",
    weight_min: "150 lbs",
    weight_max: "300 lbs",
  },
  {
    image_link:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Plains_Zebra_Equus_quagga.jpg/220px-Plains_Zebra_Equus_quagga.jpg",
    name: "Zebra",
    latin_name: "Equus zebra, Equus quagga, Equus grevyi",
    lifespan: "20 - 30 years",
    animal_type: "Mammal",
    geo_range: "Eastern and Southern Africa",
    habitat: "Open grassland and plains",
    diet: "Grasses, Leaves, Buds",
    active_time: "Diurnal",
    length_min: "6.6 ft",
    length_max: "9 ft",
    weight_min: "485 lbs",
    weight_max: "893 lbs",
  },
  {
    image_link:
      "https://upload.wikimedia.org/wikipedia/commons/9/9f/Cuttlefish_komodo_large.jpg",
    name: "Cuttlefish",
    latin_name: "Sepiida",
    lifespan: "2 years",
    animal_type: "Cephalopod",
    geo_range: "Worldwide",
    habitat: "Coastal and deeper waters",
    diet: "Crab, Shrimp, Fish",
    active_time: "Day and night",
    length_min: "5.9 in",
    length_max: "20 in",
    weight_min: "6.6 lbs",
    weight_max: "23 lbs",
  },
  {
    image_link:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Peacock_Plumage.jpg/220px-Peacock_Plumage.jpg",
    name: "Peacock",
    latin_name: "Pavo cristatus",
    lifespan: "12 - 20 years",
    animal_type: "bird",
    geo_range: "Africa and Asia",
    habitat: "Desert and savanna areas",
    diet: "Grains, Seeds, Insects",
    active_time: "Diurnal",
    length_min: "34 in",
    length_max: "42 in",
    weight_min: "6 lbs",
    weight_max: "13.2lbs",
  },
  {
    image_link:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/African_wild_dog_%28Lycaon_pictus_pictus%29.jpg/440px-African_wild_dog_%28Lycaon_pictus_pictus%29.jpg",
    name: "Painted Dog",
    latin_name: "Lycaon pictus",
    lifespan: "10 - 13 years",
    animal_type: "Mammal",
    geo_range: "sub-Saharan Africa",
    habitat: "Open plains and savanna",
    diet: "Antelope, Warthog, Rodents",
    active_time: "Diurnal",
    length_min: "29 in",
    length_max: "43 in",
    weight_min: "39 lbs",
    weight_max: "79 lbs",
  },
  {
    image_link:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Aardvark_%28Orycteropus_afer%29.jpg/440px-Aardvark_%28Orycteropus_afer%29.jpg",
    name: "Aardvark",
    latin_name: "Orycteropus afer",
    lifespan: "23 years",
    animal_type: "Mammal",
    geo_range: "sub-Saharan Africa",
    habitat: "Sandy and clay soil",
    diet: "Termites, Ants",
    active_time: "Nocturnal",
    length_min: "3.4 ft",
    length_max: "7.3ft",
    weight_min: "130 lbs",
    weight_max: "180 lbs",
  },
  {
    image_link:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Civettictis_civetta_11.jpg/440px-Civettictis_civetta_11.jpg",
    name: "African Civet",
    latin_name: "Civettictis civetta",
    lifespan: "15 - 20 years",
    animal_type: "Mammal",
    geo_range: "sub-Saharan Africa",
    habitat: "Tropical rainforest",
    diet: "Rodents, Snakes, Frogs",
    active_time: "Nocturnal",
    length_min: "2.2 ft",
    length_max: "2.8 ft",
    weight_min: "3 lbs",
    weight_max: "10 lbs",
  },
  {
    image_link:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Myresluger2.jpg/440px-Myresluger2.jpg",
    name: "Anteater",
    latin_name: "Myrmecophaga Tridactyla",
    lifespan: "9 - 20 years",
    animal_type: "Mammal",
    geo_range: "Central and South America",
    habitat: "Forest and grasslands",
    diet: "Ants, Termites, Insects",
    active_time: "Diurnal",
    length_min: "3 ft",
    length_max: "7 ft",
    weight_min: "40 lbs",
    weight_max: "88 lbs",
  },
  {
    image_link:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Aye-aye_at_night_in_the_wild_in_Madagascar.jpg/340px-Aye-aye_at_night_in_the_wild_in_Madagascar.jpg",
    name: "Aye-aye",
    latin_name: "Daubentonia madagascariensis",
    lifespan: "10 - 23 years",
    animal_type: "Mammal",
    geo_range: "Eastern coast of Madagascar",
    habitat: "Dense, tropical rainforest",
    diet: "Insects, Larvae, Fruit",
    active_time: "Nocturnal",
    length_min: "12 in",
    length_max: "15 in",
    weight_min: "4 lbs",
    weight_max: "6 lbs",
  },
  {
    image_link:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Perameles_gunni.jpg/440px-Perameles_gunni.jpg",
    name: "Bandicoot",
    latin_name: "Perameles",
    lifespan: "3-7 years",
    animal_type: "Mammal",
    geo_range: "Australia and New Guinea",
    habitat: "Forest, rainforest and jungle",
    diet: "Insects, Fruit, Seeds",
    active_time: "Nocturnal",
    length_min: "11 in",
    length_max: "32 in",
    weight_min: "0.4 lbs",
    weight_max: "3.5 lbs",
  },
  {
    image_link:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/American_Beaver.jpg/440px-American_Beaver.jpg",
    name: "Beaver",
    latin_name: "Castor",
    lifespan: "10-12 years",
    animal_type: "Mammal",
    geo_range: "",
    habitat: "Freshwater Ecosystems",
    diet: "Tree bark, Twigs, Soft Vegetation like Willows, Water Lilies, Cattails, & Watercress",
    active_time: "Nocturnal",
    length_min: "31 in",
    length_max: "47 in",
    weight_min: "24 lbs",
    weight_max: "71 lbs",
  },
  {
    image_link:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Amazona_autumnalis_-side_-Belize_Zoo-8-3c.jpg/440px-Amazona_autumnalis_-side_-Belize_Zoo-8-3c.jpg",
    name: "Amazon Parrot",
    latin_name: "Amazona",
    lifespan: "Up to 100 years",
    animal_type: "Bird",
    geo_range: "S America, Mexico, Caribbean",
    habitat:
      "Woodlands, savannas, rainforests, palm groves, cloud forests, moist forests, mountain forests",
    diet: "seeds, nuts, fruits, berries, and vegetation",
    active_time: "Diurnal",
    length_min: "10 in",
    length_max: "32 oz",
    weight_min: "7.6 oz",
    weight_max: "32 oz",
  },
  {
    image_link: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Double-wattled_Cassowary_or_Kasuari_%28Casuarius_casuarius%29.jpg/440px-Double-wattled_Cassowary_or_Kasuari_%28Casuarius_casuarius%29.jpg",
    name: "Cassowary",
    latin_name: "Casuarius",
    lifespan: "40 - 60 years",
    animal_type: "Bird",
    geo_range: "Northern Australia, New Guinea, and surrounding islands",
    habitat: "Wet tropical forests",
    diet: "Insects, Grass, Fungi",
    active_time: "Diurnal",
    length_min: "3.3 ft",
    length_max: "5.6 ft",
    weight_min: "55 lbs",
    weight_max: "129 lbs",
  },
  {
    image_link: "https://upload.wikimedia.org/wikipedia/commons/a/a3/Aptenodytes_forsteri_-Snow_Hill_Island%2C_Antarctica_-adults_and_juvenile-8.jpg",
    name: "Emporer Penguin",
    latin_name: "Aptenodytes forsteri",
    lifespan: "15 - 50 years",
    animal_type: "Bird",
    geo_range: "Antarctica",
    habitat: "Compact sea-ice and ocean",
    diet: "Fish, Krill, Squid",
    active_time: "Diurnal",
    length_min: "39 in",
    length_max: "47 in",
    weight_min: "49 lbs",
    weight_max: "99 lbs"
  },
  {
    image_link: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Balaeniceps_rex.jpg/440px-Balaeniceps_rex.jpg",
    name: "Shoebill Stork",
    latin_name: "Balaeniceps rex",
    lifespan: "Up to 35 years",
    animal_type: "Bird",
    geo_range: "East Africa",
    habitat: "Wetlands",
    diet: "Fish, snakes, frogs, turtles, lizards",
    active_time: "Diurnal",
    length_min: "3.5 ft",
    length_max: "4.5 ft",
    weight_min: "11 lbs",
    weight_max: "12 lbs"
  },
  {
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/American_Alligator.jpg/220px-American_Alligator.jpg",
    name:"American Alligator",
    latin_name:"Alligator mississippiensis",
    lifespan:"30 - 60 years",
    animal_type:"Reptile",
    geo_range:"southern USA and China",
    habitat:"Marsh and swampland",
    diet:"Fish, Snakes, Turtles",
    active_time:"Diurnal/Nocturnal",
    length_min:"8ft",
    length_max:"15ft",
    weight_min:"400lbs",
    weight_max:"800lbs"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Arizona_Black_Rattlesnake_Beauty_Shot.jpg/220px-Arizona_Black_Rattlesnake_Beauty_Shot.jpg",
    name:"Arizona Black Rattlesnake",
    latin_name:"C. cerberus",
    lifespan:"15-20 years",
    animal_type:"Reptile",
    geo_range:"North America",
    habitat:"Forests, leaf litter",
    diet:"Lizards, amphibians, small mammals, and occasionally birds",
    active_time:"Diurnal or Nocturnal Depending on Region and Season",
    length_min:"2ft",
    length_max:"4ft",
    weight_min:"2lbs",
    weight_max:"4lbs"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Western_Rat_Snake.png/220px-Western_Rat_Snake.png",
    name:"Black Rat Snake",
    latin_name:"Pantherophis obsoletus",
    lifespan:"10 to 15 years/over 30 years in captivity",
    animal_type:"Reptile",
    geo_range:"North America",
    habitat:"Farmlands, rocky areas of land, hillsides, and forests",
    diet:"Mice, frogs, birds, eggs", 
    active_time:"Diurnal",
    length_min:"3.5ft",
    length_max:"8ft",
    weight_min:"1.1lbs",
    weight_max:"4.9lbs"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Blue_iguana_%28Cyclura_lewisi%29_male.JPG/220px-Blue_iguana_%28Cyclura_lewisi%29_male.JPG",
    name:"Blue Iguana",
    latin_name:"Cyclura lewisi",
    lifespan:"25-40 years/up to 69 years in captivity",
    animal_type:"Reptile",
    geo_range:"Grand Cayman Island",
    habitat:"natural xerophytic shrubland, rocky, sunlit, open areas in dry forests or near the shore, farm clearings, roads, and gardens",
    diet:"leaves, flowers, fruits, insects, crabs, slugs and fungi",
    active_time:"Diurnal",
    length_min:"3ft",
    length_max:"5ft nose-to-tail",
    weight_min:"20lbs",
    weight_max:"30lbs"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Dispholidus_typus.jpg/220px-Dispholidus_typus.jpg",
    name:"Boomslang",
    latin_name:"Dispholidus typus",
    lifespan:"8-9 years in captivity",
    animal_type:"Reptile",
    geo_range:"sub-Saharan Africa, Swaziland, Namibia, Zimbabwe, and Mozambique",
    habitat:"wooded grasslands and lowland forests",
    diet:"Reptiles, frogs, birds, eggs, and small mammals",
    active_time:"Diurnal",
    length_min:"3.3ft",
    length_max:"6ft",
    weight_min:"0.4lbs",
    weight_max:"1.1lbs"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Brookesia_micra_on_a_match_head.jpg/220px-Brookesia_micra_on_a_match_head.jpg",
    name:"Nosy Hara leaf chameleon",
    latin_name:"Brookesia Micra",
    lifespan:"10 years in captivity, unknown in the wild",
    animal_type:"Reptile",
    geo_range:"Madagascar",
    habitat:"dry forest",
    diet:"insects",
    active_time:"Diurnal",
    length_min:"Up to",
    length_max:"1.1in",
    weight_min:"0.006oz",
    weight_max:"0.0074oz"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Brooding_female_Python_molurus_bivittatus.jpg/220px-Brooding_female_Python_molurus_bivittatus.jpg",
    name:"Burmese Python",
    latin_name:"Python bivittatus",
    lifespan:"Around 20 years",
    animal_type:"Reptile",
    geo_range:"Eastern India,Vietnam and Southern China",
    habitat:"jungles and grassy marshes",
    diet:"Mice, rabbits, and chickens",
    active_time:"Diurnal",
    length_min:"10ft",
    length_max:"20ft",
    weight_min:"30lbs",
    weight_max:"200lbs"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Caiman_yacare.jpg/220px-Caiman_yacare.jpg",
    name:"Caiman",
    latin_name:"Caiman crocodilus, Melanosuchus niger, Caiman yacare, Paleosuchus palpebrosus, Paleosuchus trigonatus, Caiman latirostris",
    lifespan:"20 - 40 years",
    animal_type:"Reptile",
    geo_range:"Central and South America",
    habitat:"Rivers, lakes and swampland",
    diet:"Fish, crustaceans, waterfowl, capybara",
    active_time:"Nocturnal",
    length_min:"4.9ft",
    length_max:"19.7ft",
    weight_min:"13lbs",
    weight_max:"660lbs"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Ball_python_lucy.JPG/220px-Ball_python_lucy.JPG",
    name:"Ball Python",
    latin_name:"Python regius",
    lifespan:"20 to 30 years",
    animal_type:"Reptile",
    geo_range:"Western and central Africa",
    habitat:"Grasslands, savannas, forests",
    diet:"Rodents, birds, amphibians, fish", 
    active_time:"Nocturnal",
    length_min:"3ft",
    length_max:"6ft",
    weight_min:"3lbs",
    weight_max:"6lbs"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Crested_gecko_-_1.jpg/220px-Crested_gecko_-_1.jpg",
    name:"Crested Gecko",
    latin_name:"Correlophus ciliatus",
    lifespan:"10 to 20 years in captivity",
    animal_type:"Reptile",
    geo_range:"New Caledonia",
    habitat:"Rainforest from 492 to 3281 feet",
    diet:"Insects, arthropods such as spiders",
    active_time:"Nocturnal",
    length_min:"6in",
    length_max:"10in",
    weight_min:"1.06oz",
    weight_max:"1.23oz"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/EpicratesAngulifer1.jpg/220px-EpicratesAngulifer1.jpg",
    name:"Cuban Boa",
    latin_name:"Chilabothrus angulifer",
    lifespan:"20+ years",
    animal_type:"Reptile",
    geo_range:"Cuba and surrounding islands",
    habitat:"rainforest, cloud forest, evergreen forest, semi-deciduous forest, thorn forest, coastal scrub forest",
    diet:"Bats, rats, birds, hutias",
    active_time:"Nocturnal Diurnal",
    length_min:"6ft",
    length_max:"21ft",
    weight_min:"24lbs",
    weight_max:"100lbs"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Gopherus_agassizii.jpg/220px-Gopherus_agassizii.jpg",
    name:"Desert Tortoise",
    latin_name:"Gopherus Agassizii",
    lifespan:"25 - 60 years",
    animal_type:"Reptile",
    geo_range:"Central and North America",
    habitat:"Sandy desert plains and rocky hills",
    diet:"Grasses, Herbs, Flowers",
    active_time:"Diurnal",
    length_min:"10in",
    length_max:"14in",
    weight_min:"8lbs",
    weight_max:"15lbs"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Cuban_Giant_Trope_%28Tropidophis_melanurus%29_%288577519420%29.jpg/220px-Cuban_Giant_Trope_%28Tropidophis_melanurus%29_%288577519420%29.jpg",
    name:"Dwarf Boa",
    latin_name:"Tropidophiidae",
    lifespan:"20+ years",
    animal_type:"Reptile",
    geo_range:"Central and South America",
    habitat:"low trees and bushes",
    diet:"small mammals, birds, lizards", 
    active_time:"Nocturnal/Crepuscular",
    length_min:"1ft",
    length_max:"6ft",
    weight_min:"10lbs",
    weight_max:"60lbs"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Eastern_Glass_Lizard.jpg/220px-Eastern_Glass_Lizard.jpg",
    name:"Eastern Glass Lizard",
    latin_name:"Ophisaurus ventralis",
    lifespan:"10 to 30 years",
    animal_type:"Reptile",
    geo_range:"Southeastern United States",
    habitat:"Wet areas",
    diet:"Lizards, snakes, mice, invertebrates such as insects, spiders, earthworms and snails",
    active_time:"Diurnal",
    length_min:"18in",
    length_max:"43in",
    weight_min:"12oz",
    weight_max:"30oz"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Varanus_prasinus.jpg/220px-Varanus_prasinus.jpg",
    name:"Emerald Tree Monitor",
    latin_name:"Varanus prasinus",
    lifespan:"10 to 15 years",
    animal_type:"Reptile",
    geo_range:"Indonesia",
    habitat:"Tropical rainforests",
    diet:"Insects, invertebrates, rodents",
    active_time:"Diurnal",
    length_min:"30in",
    length_max:"39in",
    weight_min:"10oz",
    weight_max:"11oz"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Chrysopelea_ornata.jpg/220px-Chrysopelea_ornata.jpg",
    name:"Flying Snake",
    latin_name:"Chrysopelea ornata",
    lifespan:"10 years",
    animal_type:"Reptile",
    geo_range:"Southeast Asia",
    habitat:"forests and jungles",
    diet:"Rodents, bats, birds, and their eggs, frogs, smaller snakes and lizards",
    active_time:"Diurnal",
    length_min:"2ft",
    length_max:"4ft",
    weight_min:"1.2lbs",
    weight_max:"4lbs"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Frill-necked_Lizard_%28Chlamydosaurus_kingii%29_%288692622586%29.jpg/220px-Frill-necked_Lizard_%28Chlamydosaurus_kingii%29_%288692622586%29.jpg",
    name:"Frilled Lizard",
    latin_name:"Chlamydosaurus kingii",
    lifespan:"10 - 20 years",
    animal_type:"Reptile",
    geo_range:"Oceania",
    habitat:"Tropical forests and woodland",
    diet:"Insects, Rodents, Spiders", 
    active_time:"Diurnal",
    length_min:"24in",
    length_max:"40in",
    weight_min:"1.1lbs",
    weight_max:"2.2lbs"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Thamnophis_sirtalis_sirtalis_Wooster.jpg/220px-Thamnophis_sirtalis_sirtalis_Wooster.jpg",
    name:"Garter Snake",
    latin_name:"Thamnophis sirtalis",
    lifespan:"4-10 years",
    animal_type:"Reptile",
    geo_range:"Central and North America",
    habitat:"forests, woodlands, fields, grasslands and lawns",
    diet:"Small fish, amphibians, frog eggs, lizards, leeches, earthworms, slugs, snails, insects, snails, crayfish, small birds, rodents",
    active_time:"Diurnal",
    length_min:"18in",
    length_max:"24in",
    weight_min:"4.2oz",
    weight_max:"5.3oz"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Gila_monster2.JPG/220px-Gila_monster2.JPG",
    name:"Gila Monster",
    latin_name:"Heloderma suspectum",
    lifespan:"20-30 years",
    animal_type:"Reptile",
    geo_range:"North America",
    habitat:"Shrubland, desert and woodland",
    diet:"Eggs, Small Mammals, Birds and Reptiles",
    active_time:"Diurnal",
    length_min:"18in",
    length_max:"22.5in",
    weight_min:"3lbs",
    weight_max:"5lbs"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Pituophis_catenifer_sayi_%282%29.jpg/220px-Pituophis_catenifer_sayi_%282%29.jpg",
    name:"Gopher Snake",
    latin_name:"Pituophis catenifer",
    lifespan:"15-33 years",
    animal_type:"Reptile",
    geo_range:"Central and North America",
    habitat:"woods and forests, deserts, rocky bluffs, prairies, agricultural fields, shrublands and thickets",
    diet:"Small mammals (including pocket gophers), birds, bird eggs, lizards, insects, and sometimes bats",
    active_time:"Diurnal",
    length_min:"4ft",
    length_max:"9ft",
    weight_min:"2lbs",
    weight_max:"5lbs"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Horned_lizard_032507_kdh.jpg/220px-Horned_lizard_032507_kdh.jpg",
    name:"Horned Lizard",
    latin_name:"Phrynosoma",
    lifespan:"5+ years",
    animal_type:"Reptile",
    geo_range:"North and Central America",
    habitat:"Desert and dense forest areas",
    diet:"Ants, beetles, spiders, insects", 
    active_time:"Diurnal",
    length_min:"2.5in",
    length_max:"6in",
    weight_min:"25grams",
    weight_max:"90grams"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Male_Green_Iguana_Belize.jpg/220px-Male_Green_Iguana_Belize.jpg",
    name:"Green Iguana",
    latin_name:"Iguana iguana",
    lifespan:"15-20 years",
    animal_type:"Reptile",
    geo_range:"Central, North, and South America",
    habitat:"Lowland tropical rainforest",
    diet:"Insects, Fruit, Leaves",
    active_time:"Diurnal",
    length_min:"3.9ft",
    length_max:"5.6ft nose-to-tail",
    weight_min:"8.8lbs",
    weight_max:"18lbs"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/EasternIndigo2010.jpg/220px-EasternIndigo2010.jpg",
    name:"Indigo Snake",
    latin_name:"Drymarchon couperi",
    lifespan:"25 years in captivity",
    animal_type:"Reptile",
    geo_range:"North America",
    habitat:"pine flatwoods, hardwood forests, moist hammocks, and areas that surround cypress swamps",
    diet:"Snakes, mammals, reptiles",
    active_time:"Diurnal",
    length_min:"3.9ft",
    length_max:"7.7ft",
    weight_min:"1.6lbs",
    weight_max:"9.9lbs"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Podarcis_muralis_%2815279749181%29.jpg/220px-Podarcis_muralis_%2815279749181%29.jpg",
    name:"Lazarus Lizard",
    latin_name:"Podarcis muralis",
    lifespan:"7-10 years old",
    animal_type:"Reptile",
    geo_range:"North America, northern Italy, Europe",
    habitat:"Parks, rock walls, rocky environments, urban settings",
    diet:"insects",
    active_time:"Diurnal",
    length_min:"Up to",
    length_max:"7.9in",
    weight_min:"Around",
    weight_max:"0.5oz"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Leopard_Tortoise_%28Stigmochelys_pardalis%29_%2817331907085%29.jpg/220px-Leopard_Tortoise_%28Stigmochelys_pardalis%29_%2817331907085%29.jpg",
    name:"Leopard Tortoise",
    latin_name:"Stigmochelys pardalis",
    lifespan:"50 - 100 years",
    animal_type:"Reptile",
    geo_range:"Africa",
    habitat:"Grassland and savannah",
    diet:"Grasses, Weeds, Flowers", 
    active_time:"Diurnal",
    length_min:"16in",
    length_max:"28in",
    weight_min:"40lbs",
    weight_max:"120lbs"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Massasauga_rattlesnake_1.jpg/220px-Massasauga_rattlesnake_1.jpg",
    name:"Massasauga",
    latin_name:"Sistrurus catenatus",
    lifespan:"8-14 years",
    animal_type:"Reptile",
    geo_range:"North America",
    habitat:"Prairie, marsh, and lake areas",
    diet:"Small mammals, lizards, other snakes, centipedes",
    active_time:"Diurnal",
    length_min:"24in",
    length_max:"30in",
    weight_min:"11oz",
    weight_max:"15oz"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Shimmer-of-mexican-black-kingsnake.png/220px-Shimmer-of-mexican-black-kingsnake.png",
    name:"Mexican Black Kingsnake",
    latin_name:"Lampropeltis getula nigrita",
    lifespan:" 20-30 years",
    animal_type:"Reptile",
    geo_range:" Sonora Desert, Northwestern Sinaloa, Mexico, and small parts of Arizona",
    habitat:"rocky areas and places lush with vegetation",
    diet:" rodents, snakes, eggs, and lizards",
    active_time:"Diurnal",
    length_min:"3ft",
    length_max:"4ft",
    weight_min:"3lbs",
    weight_max:"4lbs"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Red_milk_snake.JPG/220px-Red_milk_snake.JPG",
    name:"Milk Snake",
    latin_name:"Lampropeltis triangulum",
    lifespan:"3-22 years",
    animal_type:"Reptile",
    geo_range:"North America",
    habitat:"forested regions, swamps, prairie, farmland, rocky slopes, and sand dunes/beaches",
    diet:"Rodents, reptiles, snakes, and insects",
    active_time:"Nocturnal",
    length_min:"14in",
    length_max:"72in",
    weight_min:"1.3oz",
    weight_max:"3.09lbs"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Clouded_monitor_2.1.jpg/220px-Clouded_monitor_2.1.jpg",
    name:"Monitor Lizard",
    latin_name:"Varanus",
    lifespan:"8-30 years",
    animal_type:"Reptile",
    geo_range:"Africa, Asia, Oceania",
    habitat:"River banks and coastal forests",
    diet:"Rodents, Snakes, Lizards", 
    active_time:"Diurnal",
    length_min:".75ft",
    length_max:"10ft",
    weight_min:"2.2lbs",
    weight_max:"366lbs"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/NileCrocodile.jpg/250px-NileCrocodile.jpg",
    name:"Nile Crocodile",
    latin_name:"Crocodylus niloticus",
    lifespan:"45 years",
    animal_type:"Reptile",
    geo_range:"Africa",
    habitat:"Mangrove swamps, rivers, freshwater marshes",
    diet:"Fish, hippos, zebras, other crocodiles, birds",
    active_time:"Diurnal",
    length_min:"16ft",
    length_max:"20ft",
    weight_min:"500lbs",
    weight_max:"1650lbs"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Vipera-ammodytes-ruffoi-weiblich.jpg/220px-Vipera-ammodytes-ruffoi-weiblich.jpg",
    name:"Nose-horned viper",
    latin_name:"Vipera ammodytes",
    lifespan:"Up to 22 years",
    animal_type:"Reptile",
    geo_range:"Europe",
    habitat:"dry, rocky hillsides with sparse vegetation",
    diet:"Rodents, rabbits, birds",
    active_time:"Diurnal/Nocturnal",
    length_min:"2.5ft",
    length_max:"3ft",
    weight_min:"4lbs",
    weight_max:"5lbs"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Terrapene_ornata_ornata.jpg/220px-Terrapene_ornata_ornata.jpg",
    name:"Ornate Box Turtle",
    latin_name:"Terrapene Ornata",
    lifespan:"30 to 40 years",
    animal_type:"Reptile",
    geo_range:"USA",
    habitat:"plains and grasslands",
    diet:"insects",
    active_time:"Diurnal",
    length_min:"4in",
    length_max:"6in",
    weight_min:".5lbs",
    weight_max:"1.5lbs"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Naja_philippinensis.png/220px-Naja_philippinensis.png",
    name:"Philippine Cobra",
    latin_name:"Naja philippinensis",
    lifespan:"20+ years",
    animal_type:"Reptile",
    geo_range:"northern regions of the Philippines",
    habitat:"low-lying plains, forested regions, open fields, grasslands, dense jungle, agricultural fields, and human settlements",
    diet:"Rodents, other small mammals, frogs, reptiles, eggs", 
    active_time:"Diurnal",
    length_min:"3.3ft",
    length_max:"5+ft",
    weight_min:"15lbs",
    weight_max:"19lbs"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/EpicratesCenchriaCenchria1.jpg/220px-EpicratesCenchriaCenchria1.jpg",
    name:"Rainbow Boa",
    latin_name:"Epicrates cenchria",
    lifespan:"20+ years",
    animal_type:"Reptile",
    geo_range:"lower Central America and South America",
    habitat:"humid woodlands and rainforests",
    diet:"Rodents, small birds, small lizards, some aquatic animals",
    active_time:"Nocturnal",
    length_min:"4ft",
    length_max:"6ft",
    weight_min:"2lbs",
    weight_max:"5lbs"
},
{
    image_link:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Crotalus_ruber_02.jpg/220px-Crotalus_ruber_02.jpg",
    name:"Red Diamondback Rattlesnake",
    latin_name:"Crotalus ruber",
    lifespan:"13-15 years",
    animal_type:"Reptile",
    geo_range:"Baja California and southwestern California, US",
    habitat:"coastal scrub brush, desert",
    diet:"mice, rats, rabbits, squirrels, lizards, snakes",
    active_time:"Diurnal/Nocturnal",
    length_min:"39in",
    length_max:"59in",
    weight_min:"3lbs",
    weight_max:"5lbs"
},
  // {
  //     image_link:"",
  //     name:"",
  //     latin_name:"",
  //     lifespan:"",
  //     animal_type:"",
  //     geo_range:"",
  //     habitat:"",
  //     diet:"",
  //     active_time:"",
  //     length_min:"",
  //     length_max:"",
  //     weight_min:" lbs",
  //     weight_max:" lbs"
  // },
  // {
  //     image_link:"",
  //     name:"",
  //     latin_name:"",
  //     lifespan:"",
  //     animal_type:"",
  //     geo_range:"",
  //     habitat:"",
  //     diet:"",
  //     active_time:"",
  //     length_min:"",
  //     length_max:"",
  //     weight_min:" lbs",
  //     weight_max:" lbs"
  // },
  // {
  //     image_link:"",
  //     name:"",
  //     latin_name:"",
  //     lifespan:"",
  //     animal_type:"",
  //     geo_range:"",
  //     habitat:"",
  //     diet:"",
  //     active_time:"",
  //     length_min:"",
  //     length_max:"",
  //     weight_min:" lbs",
  //     weight_max:" lbs"
  // },
];
const seedData = async () => {
  await sequelize.sync({ force: true });
  const animals = await Animal.bulkCreate(animalData);
};
seedData();
